import type { Language, PositionReading, TarotSpread } from "../types";
import { formatTarotKnowledgeForPrompt, getDisplayKeywords } from "./tarotCardKnowledge";

type BuildSummaryAgentPromptArgs = {
  language: Language;
  originalQuestion: string;
  spread: TarotSpread;
  positionReadings: PositionReading[];
  choiceA?: string;
  choiceB?: string;
};

export function buildSummaryAgentPrompt({
  language,
  originalQuestion,
  spread,
  positionReadings,
  choiceA,
  choiceB
}: BuildSummaryAgentPromptArgs): string {
  const zh = language === "zh";
  const readings = positionReadings.map((reading) => formatReading(reading, language)).join("\n\n");
  const allUserInputs = formatUserInputs(positionReadings, language);
  const keywordIndex = formatKeywordIndex(positionReadings, language);

  return `
You are an experienced tarot reader synthesizing a completed spread.

You do not predict fate.
You do not give deterministic advice.
You do not write a mechanical position-by-position report.
You read the spread as a whole, but every claim must stay grounded in the evidence below.
Do not call yourself a fortune-teller, master, or therapist.

Your task:
Return the user's journey through the spread in plain reader-facing language.
Keep the user's content and tarot reasoning, but translate abstract analysis into short, concrete paragraphs.
The result should feel like a good tarot reader speaking clearly, not like a theory report.

Use all available evidence:
- original question
- A/B options if present
- spread name and position meanings
- every card and its local card information
- user's first observation for each card
- every user answer in every position
- ultimate questions and core insights generated by each position
- keyword index across cards

Look for:
- repeated card keywords and image patterns
- contradictions between positions
- tensions between what the user wants and what they avoids
- missing voices or unspoken criteria
- how the user's own words changed the reading
- whether the spread suggests a direction, while keeping the conclusion non-absolute

Style:
- Return all prose in ${zh ? "Simplified Chinese" : "English"}.
- Be specific. Do not say only ${zh ? "“资源”“界限”“能量”“转化”“内在”" : "\"energy,\" \"boundaries,\" \"transformation,\" or \"inner truth\""} unless you immediately say what that means in the user's actual situation.
- Prefer everyday verbs: ${zh ? "看清、分清、少扛一点、先问清楚、从小处推动、留一点力气" : "notice, separate, ask clearly, carry less, make one small move, save energy"}.
- You may help the user see a direction, but phrase it as ${zh ? "“这副牌更像是在提醒你……”“这几天可以先……”" : "\"this spread seems to remind you...\" or \"for now, you can first...\""}.
- Include a practical, gentle suggestion if the spread contains enough evidence. If evidence is weak, say what would need clarification.
- Keep the small poetic closing restrained, or make it a single quiet image.

Reader-facing structure:
- title: short and clear. Name the real-life focus, not an abstract theme.
- overview: 2-4 short paragraphs. Start with the main takeaway in plain language. Then explain the spread in order. For each important card, use this pattern: ${zh ? "“《牌名》说明/提醒……所以在这件事里……”" : "\"Card Name suggests/reminds... so in this situation...\""}.
- deepPattern: 1 short paragraph. Name the repeated pattern in direct language. Do not repeat the overview.
- questionToCarry: 1-2 short questions. Each question must be easy to answer from daily life. No compound questions.
- gentleSuggestion: 2-4 practical sentences. Mention one small next move and one thing not to over-carry.
- smallPoem: maximum 4 short lines.

Compression rules:
- Keep the whole summary concise: ${zh ? "约 450-700 个中文字；不要超过 850 个中文字" : "about 300-500 words; never over 650 words"}.
- No paragraph should contain more than 3 sentences.
- Do not list many abstract nouns in a row.
- If two sentences say the same thing with different abstract words, keep the clearer one.
- Do not write a mechanical position-by-position report, but do let the reader understand what each card contributed.

Original question:
${originalQuestion}

Spread:
${zh ? spread.nameZh : spread.nameEn} (${spread.id})

Spread map:
${formatSpreadMap(spread, language)}

${choiceA || choiceB ? `Choice A: ${choiceA || "(not provided)"}\nChoice B: ${choiceB || "(not provided)"}` : ""}

All user inputs:
${allUserInputs}

Keyword index:
${keywordIndex}

Position evidence packets:
${readings}

Return structured JSON only:
{
  "type": "spread_summary",
  "title": "...",
  "overview": "...",
  "deepPattern": "...",
  "questionToCarry": "...",
  "gentleSuggestion": "...",
  "smallPoem": "..."
}
`.trim();
}

function formatSpreadMap(spread: TarotSpread, language: Language): string {
  return spread.positions
    .slice()
    .sort((a, b) => a.order - b.order)
    .map((position) => {
      const title = language === "zh" ? position.titleZh : position.titleEn;
      const question = language === "zh" ? position.positionQuestionZh : position.positionQuestionEn;
      return `${position.order}. ${title}: ${question}`;
    })
    .join("\n");
}

function formatReading(reading: PositionReading, language: Language): string {
  const card = reading.card ? `${reading.card.nameEn} / ${reading.card.nameZh}` : "No card";
  const keywords = reading.card ? getDisplayKeywords(reading.card, language).join(", ") : "none";
  const observation = reading.userObservation || "No user observation.";
  const dialogue = reading.dialogue.map((message) => `${message.role}: ${message.content}`).join("\n");

  return [
    `${reading.positionOrder}. ${reading.positionTitleEn} / ${reading.positionTitleZh}`,
    `Status: ${reading.status}`,
    `Position question: ${reading.positionQuestionEn} / ${reading.positionQuestionZh}`,
    `Card: ${card}`,
    `Card keywords: ${keywords}`,
    `Card information:`,
    formatTarotKnowledgeForPrompt(reading.card, language),
    `User observation: ${observation}`,
    `Question left: ${reading.ultimateQuestionEn || reading.ultimateQuestionZh || "none"}`,
    `Core insight: ${reading.coreInsightEn || reading.coreInsightZh || "none"}`,
    `Dialogue: ${dialogue || "none"}`
  ].join("\n");
}

function formatUserInputs(positionReadings: PositionReading[], language: Language): string {
  const inputs: string[] = [];
  for (const reading of positionReadings.slice().sort((a, b) => a.positionOrder - b.positionOrder)) {
    if (reading.userObservation) inputs.push(`- Position ${reading.positionOrder} observation: ${reading.userObservation}`);
    for (const message of reading.dialogue) {
      if (message.role === "user") inputs.push(`- Position ${reading.positionOrder} user: ${message.content}`);
    }
  }
  return inputs.length ? inputs.join("\n") : language === "zh" ? "除原问题外，暂无更多用户输入。" : "No user inputs beyond the original question.";
}

function formatKeywordIndex(positionReadings: PositionReading[], language: Language): string {
  const entries = new Map<string, string[]>();
  for (const reading of positionReadings) {
    if (!reading.card) continue;
    const title = language === "zh" ? reading.positionTitleZh : reading.positionTitleEn;
    for (const keyword of getDisplayKeywords(reading.card, language)) {
      const current = entries.get(keyword) || [];
      current.push(`${reading.positionOrder}. ${title}`);
      entries.set(keyword, current);
    }
  }
  if (!entries.size) return "No card keywords available.";
  return [...entries.entries()].map(([keyword, positions]) => `- ${keyword}: ${positions.join("; ")}`).join("\n");
}
