import type { Language, PositionReading, TarotSpread } from "../types";
import { formatTarotKnowledgeForPrompt, getDisplayKeywords } from "./tarotCardKnowledge";

type BuildSummaryAgentPromptArgs = {
  language: Language;
  originalQuestion: string;
  spread: TarotSpread;
  positionReadings: PositionReading[];
  choiceA?: string;
  choiceB?: string;
};

export function buildSummaryAgentPrompt({
  language,
  originalQuestion,
  spread,
  positionReadings,
  choiceA,
  choiceB
}: BuildSummaryAgentPromptArgs): string {
  const zh = language === "zh";
  const readings = positionReadings.map((reading) => formatReading(reading, language)).join("\n\n");
  const allUserInputs = formatUserInputs(positionReadings, language);
  const keywordIndex = formatKeywordIndex(positionReadings, language);

  return `
You are an experienced tarot reader synthesizing a completed spread.

You do not predict fate.
You do not give deterministic advice.
You do not write a mechanical position-by-position report.
You read the spread as a whole, but every claim must stay grounded in the evidence below.
Do not call yourself a fortune-teller, master, or therapist.

Your task:
Return the user's journey through the spread in a clearer, warmer, more meaningful form.

Use all available evidence:
- original question
- A/B options if present
- spread name and position meanings
- every card and its local card information
- user's first observation for each card
- every user answer in every position
- ultimate questions and core insights generated by each position
- keyword index across cards

Look for:
- repeated card keywords and image patterns
- contradictions between positions
- tensions between what the user wants and what they avoids
- missing voices or unspoken criteria
- how the user's own words changed the reading
- whether the spread suggests a direction, while keeping the conclusion non-absolute

Style:
- Return all prose in ${zh ? "Simplified Chinese" : "English"}.
- Be specific. Do not say only ${zh ? "“你需要倾听内心”或“这是一段转化”" : "\"listen to your heart\" or \"this is a transformation\""} without naming what in the cards or user inputs supports it.
- You may help the user see a direction, but phrase it as ${zh ? "“这副牌更像是在把你带向……”“可以优先留意……”" : "\"this spread seems to point toward...\" or \"it may be worth prioritizing...\""}.
- Include a practical, gentle suggestion if the spread contains enough evidence. If evidence is weak, say what would need clarification.
- Keep the small poetic closing restrained.

Original question:
${originalQuestion}

Spread:
${zh ? spread.nameZh : spread.nameEn} (${spread.id})

Spread map:
${formatSpreadMap(spread, language)}

${choiceA || choiceB ? `Choice A: ${choiceA || "(not provided)"}\nChoice B: ${choiceB || "(not provided)"}` : ""}

All user inputs:
${allUserInputs}

Keyword index:
${keywordIndex}

Position evidence packets:
${readings}

Return structured JSON only:
{
  "type": "spread_summary",
  "title": "...",
  "overview": "...",
  "deepPattern": "...",
  "questionToCarry": "...",
  "gentleSuggestion": "...",
  "smallPoem": "..."
}
`.trim();
}

function formatSpreadMap(spread: TarotSpread, language: Language): string {
  return spread.positions
    .slice()
    .sort((a, b) => a.order - b.order)
    .map((position) => {
      const title = language === "zh" ? position.titleZh : position.titleEn;
      const question = language === "zh" ? position.positionQuestionZh : position.positionQuestionEn;
      return `${position.order}. ${title}: ${question}`;
    })
    .join("\n");
}

function formatReading(reading: PositionReading, language: Language): string {
  const card = reading.card ? `${reading.card.nameEn} / ${reading.card.nameZh}` : "No card";
  const keywords = reading.card ? getDisplayKeywords(reading.card, language).join(", ") : "none";
  const observation = reading.userObservation || "No user observation.";
  const dialogue = reading.dialogue.map((message) => `${message.role}: ${message.content}`).join("\n");

  return [
    `${reading.positionOrder}. ${reading.positionTitleEn} / ${reading.positionTitleZh}`,
    `Status: ${reading.status}`,
    `Position question: ${reading.positionQuestionEn} / ${reading.positionQuestionZh}`,
    `Card: ${card}`,
    `Card keywords: ${keywords}`,
    `Card information:`,
    formatTarotKnowledgeForPrompt(reading.card, language),
    `User observation: ${observation}`,
    `Question left: ${reading.ultimateQuestionEn || reading.ultimateQuestionZh || "none"}`,
    `Core insight: ${reading.coreInsightEn || reading.coreInsightZh || "none"}`,
    `Dialogue: ${dialogue || "none"}`
  ].join("\n");
}

function formatUserInputs(positionReadings: PositionReading[], language: Language): string {
  const inputs: string[] = [];
  for (const reading of positionReadings.slice().sort((a, b) => a.positionOrder - b.positionOrder)) {
    if (reading.userObservation) inputs.push(`- Position ${reading.positionOrder} observation: ${reading.userObservation}`);
    for (const message of reading.dialogue) {
      if (message.role === "user") inputs.push(`- Position ${reading.positionOrder} user: ${message.content}`);
    }
  }
  return inputs.length ? inputs.join("\n") : language === "zh" ? "除原问题外，暂无更多用户输入。" : "No user inputs beyond the original question.";
}

function formatKeywordIndex(positionReadings: PositionReading[], language: Language): string {
  const entries = new Map<string, string[]>();
  for (const reading of positionReadings) {
    if (!reading.card) continue;
    const title = language === "zh" ? reading.positionTitleZh : reading.positionTitleEn;
    for (const keyword of getDisplayKeywords(reading.card, language)) {
      const current = entries.get(keyword) || [];
      current.push(`${reading.positionOrder}. ${title}`);
      entries.set(keyword, current);
    }
  }
  if (!entries.size) return "No card keywords available.";
  return [...entries.entries()].map(([keyword, positions]) => `- ${keyword}: ${positions.join("; ")}`).join("\n");
}
