export type TarotCard = {
  id: string;
  englishName: string;
  chineseName: string;
  keywords: string[];
  symbolicFunction: string;
  reflectiveOperation: string;
  visualSymbol: string;
  coreMeaningEn: string;
  coreMeaningZh: string;
  allowedThemes: string[];
  avoidThemes: string[];
  reflectiveDirectionEn: string;
  reflectiveDirectionZh: string;
  reframingStyle: string;
};

export const majorArcana: TarotCard[] = [
  {
    id: "the-fool",
    englishName: "The Fool",
    chineseName: "愚者",
    keywords: ["threshold", "risk", "beginning", "innocence"],
    symbolicFunction: "This card interrupts the demand to know before beginning.",
    reflectiveOperation: "It asks what might open if uncertainty became part of the method.",
    visualSymbol: "open circle / cliff line",
    coreMeaningEn: "beginnings, risk, not-knowing, and the threshold before a path is named.",
    coreMeaningZh: "开始、冒险、尚未知道，以及道路被命名前的门槛。",
    allowedThemes: ["beginning", "risk", "threshold", "not knowing", "openness", "first step"],
    avoidThemes: ["fixed conclusion", "cynicism", "productivity plan", "certainty", "final proof"],
    reflectiveDirectionEn: "Turn the question from certainty toward what can begin without certainty.",
    reflectiveDirectionZh: "把问题从确定答案转向：在不确定中什么仍然可以开始。",
    reframingStyle: "Ask what first step is possible before the user feels ready."
  },
  {
    id: "the-magician",
    englishName: "The Magician",
    chineseName: "魔术师",
    keywords: ["agency", "tools", "attention", "transformation"],
    symbolicFunction: "This card interrupts helplessness by noticing available tools.",
    reflectiveOperation: "It asks what is already in your hands, and what you are doing with it.",
    visualSymbol: "wand / table",
    coreMeaningEn: "agency, attention, available tools, and the act of turning intention into form.",
    coreMeaningZh: "能动性、注意力、手边的工具，以及把意图变成形式的动作。",
    allowedThemes: ["agency", "tools", "attention", "skill", "intention", "making"],
    avoidThemes: ["helplessness as identity", "fate prediction", "passive waiting", "pure emotion without action"],
    reflectiveDirectionEn: "Turn the question toward what is already available and how attention is being used.",
    reflectiveDirectionZh: "把问题转向：你已经拥有什么，以及注意力正在如何被使用。",
    reframingStyle: "Ask what the user can make with the tools already present."
  },
  {
    id: "the-high-priestess",
    englishName: "The High Priestess",
    chineseName: "女祭司",
    keywords: ["intuition", "secrecy", "silence", "threshold"],
    symbolicFunction: "This card interrupts over-explanation.",
    reflectiveOperation: "It asks what is known quietly, withheld, or not yet ready to be spoken.",
    visualSymbol: "veil / crescent",
    coreMeaningEn: "hidden intuition, unspoken feelings, and knowledge that has not yet become clear.",
    coreMeaningZh: "隐藏的直觉、未说出口的感受、暂时无法被理性证明的知道。",
    allowedThemes: ["intuition", "hidden feeling", "silence", "inner knowing", "unspoken truth", "waiting before action"],
    avoidThemes: ["external achievement", "productivity advice", "direct action plan", "social performance"],
    reflectiveDirectionEn: "Turn the question from external solving toward internal listening.",
    reflectiveDirectionZh: "把问题从外部解决转向内部倾听。",
    reframingStyle: "Ask what the user already senses but has not yet admitted."
  },
  {
    id: "the-empress",
    englishName: "The Empress",
    chineseName: "皇后",
    keywords: ["care", "growth", "body", "abundance"],
    symbolicFunction: "This card interrupts scarcity as the only frame.",
    reflectiveOperation: "It asks what needs tending before it can answer back.",
    visualSymbol: "grain / garden",
    coreMeaningEn: "care, growth, embodiment, nourishment, and what needs time to ripen.",
    coreMeaningZh: "照料、生长、身体感受、滋养，以及需要时间成熟的东西。",
    allowedThemes: ["care", "body", "growth", "nourishment", "receiving", "creative fertility"],
    avoidThemes: ["cold efficiency", "punishment", "collapse", "detachment", "pure rational proof"],
    reflectiveDirectionEn: "Turn the question toward what needs care before it can become clear.",
    reflectiveDirectionZh: "把问题转向：什么需要先被照料，才可能变清楚。",
    reframingStyle: "Ask what part of the situation is asking to be tended rather than solved."
  },
  {
    id: "the-emperor",
    englishName: "The Emperor",
    chineseName: "皇帝",
    keywords: ["structure", "boundary", "authority", "order"],
    symbolicFunction: "This card interrupts drifting by revealing structure.",
    reflectiveOperation: "It asks which rules are protecting you and which are enclosing you.",
    visualSymbol: "square / throne",
    coreMeaningEn: "structure, boundaries, authority, order, and the cost of control.",
    coreMeaningZh: "结构、边界、权威、秩序，以及控制所付出的代价。",
    allowedThemes: ["structure", "boundary", "authority", "control", "responsibility", "protection"],
    avoidThemes: ["dreamy ambiguity", "romantic harmony", "collapse for its own sake", "passive drifting"],
    reflectiveDirectionEn: "Turn the question toward the rules, boundaries, and authorities shaping it.",
    reflectiveDirectionZh: "把问题转向：哪些规则、边界和权威正在塑造它。",
    reframingStyle: "Ask which structure protects the user and which structure confines them."
  },
  {
    id: "the-hierophant",
    englishName: "The Hierophant",
    chineseName: "教皇",
    keywords: ["tradition", "institution", "teaching", "belonging"],
    symbolicFunction: "This card interrupts the fantasy of being outside all systems.",
    reflectiveOperation: "It asks whose rules, rituals, or inherited voices are shaping the question.",
    visualSymbol: "keys / pillars",
    coreMeaningEn: "tradition, inherited rules, institutions, teaching, and belonging to a shared order.",
    coreMeaningZh: "传统、继承来的规则、制度、教导，以及对共同秩序的归属。",
    allowedThemes: ["tradition", "institution", "belief", "teaching", "belonging", "inherited rule"],
    avoidThemes: ["pure individualism", "instant rebellion", "private intuition only", "randomness"],
    reflectiveDirectionEn: "Turn the question toward the inherited rule or institution speaking through it.",
    reflectiveDirectionZh: "把问题转向：哪条继承来的规则或制度正在借它说话。",
    reframingStyle: "Ask whose voice the user is treating as truth."
  },
  {
    id: "the-lovers",
    englishName: "The Lovers",
    chineseName: "恋人",
    keywords: ["choice", "relationship", "alignment"],
    symbolicFunction: "This card interrupts binary thinking.",
    reflectiveOperation: "It asks what third path may exist beyond yes or no.",
    visualSymbol: "two figures / shared star",
    coreMeaningEn: "choice, relationship, desire, alignment, and the third path beyond a false binary.",
    coreMeaningZh: "选择、关系、价值对齐、欲望，以及二选一之外的第三种可能。",
    allowedThemes: ["choice", "relationship", "alignment", "desire", "third path", "values"],
    avoidThemes: ["collapse", "isolation", "pure productivity", "fate prediction"],
    reflectiveDirectionEn: "Turn the question from yes/no toward relationship, values, and a third path.",
    reflectiveDirectionZh: "把问题从 yes/no 转向关系、价值和第三条路。",
    reframingStyle: "Ask what the user is actually choosing between."
  },
  {
    id: "the-chariot",
    englishName: "The Chariot",
    chineseName: "战车",
    keywords: ["direction", "will", "motion", "tension"],
    symbolicFunction: "This card interrupts passive waiting.",
    reflectiveOperation: "It asks what competing forces are being held together by effort.",
    visualSymbol: "wheels / reins",
    coreMeaningEn: "direction, will, disciplined movement, and opposing forces held in motion.",
    coreMeaningZh: "方向、意志、有纪律的移动，以及被努力拉在一起的相反力量。",
    allowedThemes: ["direction", "will", "movement", "discipline", "tension", "momentum"],
    avoidThemes: ["stillness as final answer", "surrender", "romantic harmony", "vague waiting"],
    reflectiveDirectionEn: "Turn the question toward what is pulling in different directions and what is steering.",
    reflectiveDirectionZh: "把问题转向：哪些力量在相互拉扯，以及谁在掌舵。",
    reframingStyle: "Ask what force needs to be guided rather than suppressed."
  },
  {
    id: "strength",
    englishName: "Strength",
    chineseName: "力量",
    keywords: ["gentleness", "courage", "patience", "influence"],
    symbolicFunction: "This card interrupts force as the only form of power.",
    reflectiveOperation: "It asks where softness may be more exact than pressure.",
    visualSymbol: "lion / lemniscate",
    coreMeaningEn: "gentle courage, patience, inner steadiness, and influence without domination.",
    coreMeaningZh: "温柔的勇气、耐心、内在稳定，以及不靠支配的影响力。",
    allowedThemes: ["gentleness", "courage", "patience", "self-trust", "soft power", "taming intensity"],
    avoidThemes: ["domination", "speed", "collapse", "cold logic", "self-punishment"],
    reflectiveDirectionEn: "Turn the question from force toward steadiness and tender courage.",
    reflectiveDirectionZh: "把问题从用力推进转向稳定、温柔和勇气。",
    reframingStyle: "Ask where gentleness could be a stronger form of power."
  },
  {
    id: "the-hermit",
    englishName: "The Hermit",
    chineseName: "隐士",
    keywords: ["solitude", "lantern", "distance", "inner witness"],
    symbolicFunction: "This card interrupts the need for immediate audience.",
    reflectiveOperation: "It asks what becomes visible when the question is held at a distance.",
    visualSymbol: "lantern / mountain",
    coreMeaningEn: "solitude, distance, inner witness, and the small light found away from noise.",
    coreMeaningZh: "独处、距离、内在见证者，以及离开噪音后看见的小光。",
    allowedThemes: ["solitude", "distance", "inner witness", "discernment", "privacy", "slow insight"],
    avoidThemes: ["social performance", "crowd approval", "instant action", "romantic merging"],
    reflectiveDirectionEn: "Turn the question toward what can only be seen with distance.",
    reflectiveDirectionZh: "把问题转向：保持距离后才看得见的东西。",
    reframingStyle: "Ask what the user knows when no one else is watching."
  },
  {
    id: "wheel-of-fortune",
    englishName: "Wheel of Fortune",
    chineseName: "命运之轮",
    keywords: ["cycle", "chance", "recurrence", "turning"],
    symbolicFunction: "This card interrupts the illusion that the current moment is fixed.",
    reflectiveOperation: "It asks what pattern is returning and what can be learned from its turn.",
    visualSymbol: "wheel / four marks",
    coreMeaningEn: "cycles, turning points, recurrence, chance, and the pattern that keeps returning.",
    coreMeaningZh: "循环、转折、反复出现、偶然，以及不断回来的模式。",
    allowedThemes: ["cycle", "recurrence", "turning point", "pattern", "chance", "timing"],
    avoidThemes: ["permanent identity", "fixed conclusion", "total control", "linear progress only"],
    reflectiveDirectionEn: "Turn the question toward the repeating pattern and the moment of turning.",
    reflectiveDirectionZh: "把问题转向：什么模式正在重复，以及转动发生在哪里。",
    reframingStyle: "Ask what returns each time and what changes in the return."
  },
  {
    id: "justice",
    englishName: "Justice",
    chineseName: "正义",
    keywords: ["balance", "consequence", "truth", "accountability"],
    symbolicFunction: "This card interrupts emotional fog with proportion.",
    reflectiveOperation: "It asks what would change if fairness, evidence, and consequence were named.",
    visualSymbol: "scales / sword",
    coreMeaningEn: "fairness, consequence, accountability, proportion, and the truth that asks to be named.",
    coreMeaningZh: "公平、后果、责任、比例，以及需要被说出的真相。",
    allowedThemes: ["fairness", "accountability", "truth", "consequence", "balance", "evidence"],
    avoidThemes: ["avoidance", "vague comfort", "fate prediction", "hidden intuition as proof"],
    reflectiveDirectionEn: "Turn the question toward fairness, responsibility, and what has consequences.",
    reflectiveDirectionZh: "把问题转向：公平、责任，以及哪些事会产生后果。",
    reframingStyle: "Ask what would have to be named for the situation to become fair."
  },
  {
    id: "the-hanged-man",
    englishName: "The Hanged Man",
    chineseName: "倒吊人",
    keywords: ["pause", "reversal", "suspension", "seeing differently"],
    symbolicFunction: "This card interrupts the need to move forward.",
    reflectiveOperation: "It asks whether stillness, delay, or discomfort may reveal something movement has been hiding.",
    visualSymbol: "inverted triangle / suspended line",
    coreMeaningEn: "pause, suspension, reversal, and seeing differently while movement is interrupted.",
    coreMeaningZh: "暂停、悬置、倒转，以及行动被打断后出现的另一种看法。",
    allowedThemes: ["pause", "suspension", "reversal", "surrender", "delay", "new perspective"],
    avoidThemes: ["immediate solution", "productivity", "force", "certainty", "escape"],
    reflectiveDirectionEn: "Turn the question from moving forward toward what the pause reveals.",
    reflectiveDirectionZh: "把问题从继续前进转向：暂停本身正在显露什么。",
    reframingStyle: "Ask what becomes visible only because the user cannot move yet."
  },
  {
    id: "death",
    englishName: "Death",
    chineseName: "死神",
    keywords: ["ending", "change", "release", "compost"],
    symbolicFunction: "This card interrupts the wish to keep every form alive.",
    reflectiveOperation: "It asks what may need to end as a form so something else can continue.",
    visualSymbol: "scythe / sunrise",
    coreMeaningEn: "ending, release, transition, and the form that must pass so life can change.",
    coreMeaningZh: "结束、放手、转化，以及必须退场才让生命改变的旧形式。",
    allowedThemes: ["ending", "release", "transition", "letting go", "change", "old form"],
    avoidThemes: ["simple comfort", "status quo", "minor adjustment", "romantic harmony"],
    reflectiveDirectionEn: "Turn the question toward what is ending and what cannot continue in its old form.",
    reflectiveDirectionZh: "把问题转向：什么正在结束，什么不能再以旧形式继续。",
    reframingStyle: "Ask what the user is still carrying that has already ended."
  },
  {
    id: "temperance",
    englishName: "Temperance",
    chineseName: "节制",
    keywords: ["mixing", "patience", "proportion", "healing"],
    symbolicFunction: "This card interrupts extremes.",
    reflectiveOperation: "It asks what could be blended, slowed, or remeasured.",
    visualSymbol: "two cups / flowing line",
    coreMeaningEn: "proportion, blending, patience, repair, and the slow adjustment between extremes.",
    coreMeaningZh: "比例、调和、耐心、修复，以及极端之间缓慢的调整。",
    allowedThemes: ["balance", "blending", "patience", "moderation", "repair", "proportion"],
    avoidThemes: ["extreme decision", "collapse", "rush", "purity", "all-or-nothing"],
    reflectiveDirectionEn: "Turn the question toward what needs mixing, pacing, or rebalancing.",
    reflectiveDirectionZh: "把问题转向：什么需要调和、放慢或重新配比。",
    reframingStyle: "Ask what two things need to be held together in a different proportion."
  },
  {
    id: "the-devil",
    englishName: "The Devil",
    chineseName: "恶魔",
    keywords: ["attachment", "appetite", "pattern", "bargain"],
    symbolicFunction: "This card interrupts innocence about the bargain being made.",
    reflectiveOperation: "It asks what binds you, what rewards the binding, and what names it avoids.",
    visualSymbol: "chains / flame",
    coreMeaningEn: "attachment, appetite, compulsion, bargains, and the reward hidden inside a binding pattern.",
    coreMeaningZh: "依附、欲望、强迫、交换，以及束缚模式里隐藏的回报。",
    allowedThemes: ["attachment", "compulsion", "desire", "bargain", "habit", "shadow reward"],
    avoidThemes: ["innocent purity", "simple moralizing", "fate prediction", "gentle patience only"],
    reflectiveDirectionEn: "Turn the question toward what binds the user and what the binding gives back.",
    reflectiveDirectionZh: "把问题转向：什么在束缚你，以及这种束缚给了你什么回报。",
    reframingStyle: "Ask what the user receives from the pattern they also want to leave."
  },
  {
    id: "the-tower",
    englishName: "The Tower",
    chineseName: "高塔",
    keywords: ["collapse", "disruption", "broken assumption"],
    symbolicFunction: "This card interrupts the structure of the question.",
    reflectiveOperation: "It asks what assumption may need to break before the question can change.",
    visualSymbol: "tower / lightning",
    coreMeaningEn: "collapse, disruption, broken assumptions, and the truth exposed after a structure fails.",
    coreMeaningZh: "结构的破裂、旧假设的崩塌、无法继续维持的东西。",
    allowedThemes: ["collapse", "broken assumption", "forced change", "unsustainable structure", "truth after disruption"],
    avoidThemes: ["gentle patience", "hidden intuition", "romantic harmony", "simple comfort"],
    reflectiveDirectionEn: "Turn the question toward what can no longer be maintained.",
    reflectiveDirectionZh: "把问题转向：什么东西已经无法继续维持？",
    reframingStyle: "Ask what assumption must break before the question can move."
  },
  {
    id: "the-star",
    englishName: "The Star",
    chineseName: "星星",
    keywords: ["hope", "repair", "quiet wish"],
    symbolicFunction: "This card interrupts despair without forcing optimism.",
    reflectiveOperation: "It asks what gentle hope remains when proof and performance are removed.",
    visualSymbol: "star / water",
    coreMeaningEn: "quiet hope, repair, vulnerability, and the wish that remains after exhaustion.",
    coreMeaningZh: "安静的希望、修复、脆弱，以及疲惫之后仍然留下的愿望。",
    allowedThemes: ["hope", "repair", "vulnerability", "wish", "renewal", "gentle future"],
    avoidThemes: ["collapse", "cynicism", "hard control", "punishment", "instant certainty"],
    reflectiveDirectionEn: "Turn the question toward the small hope that remains without performance.",
    reflectiveDirectionZh: "把问题转向：不再表演之后，仍然留下的微弱希望。",
    reframingStyle: "Ask what hope remains when the user stops needing proof."
  },
  {
    id: "the-moon",
    englishName: "The Moon",
    chineseName: "月亮",
    keywords: ["uncertainty", "dream", "fear", "hidden truth"],
    symbolicFunction: "This card interrupts the desire for immediate clarity.",
    reflectiveOperation: "It asks what is imagined, feared, unclear, or unsaid.",
    visualSymbol: "moon / path",
    coreMeaningEn: "uncertainty, fear, imagination, projection, and facts not yet clearly seen.",
    coreMeaningZh: "模糊、恐惧、想象、误读、尚未看清的事实。",
    allowedThemes: ["uncertainty", "fear", "projection", "dream", "confusion", "unknown"],
    avoidThemes: ["clear certainty", "definite advice", "rational proof", "fixed conclusion"],
    reflectiveDirectionEn: "Turn the question toward what is fact, what is fear, and what is imagination.",
    reflectiveDirectionZh: "把问题转向：什么是事实，什么是恐惧，什么是想象？",
    reframingStyle: "Ask the user to separate fear from fact."
  },
  {
    id: "the-sun",
    englishName: "The Sun",
    chineseName: "太阳",
    keywords: ["clarity", "warmth", "exposure", "vitality"],
    symbolicFunction: "This card interrupts secrecy with daylight.",
    reflectiveOperation: "It asks what becomes simpler when it is allowed to be seen.",
    visualSymbol: "sun / rays",
    coreMeaningEn: "clarity, warmth, exposure, vitality, and what becomes simple in daylight.",
    coreMeaningZh: "清晰、温暖、显露、生命力，以及在日光下变简单的东西。",
    allowedThemes: ["clarity", "visibility", "joy", "warmth", "honesty", "vitality"],
    avoidThemes: ["hidden secrecy", "fearful projection", "collapse", "overcomplication"],
    reflectiveDirectionEn: "Turn the question toward what becomes clearer when it is plainly seen.",
    reflectiveDirectionZh: "把问题转向：被清楚看见之后，什么会变简单。",
    reframingStyle: "Ask what truth becomes easier when brought into daylight."
  },
  {
    id: "judgement",
    englishName: "Judgement",
    chineseName: "审判",
    keywords: ["calling", "return", "reckoning", "awakening"],
    symbolicFunction: "This card interrupts the old version of the story.",
    reflectiveOperation: "It asks what is calling to be answered differently now.",
    visualSymbol: "trumpet / rising line",
    coreMeaningEn: "calling, reckoning, return, awakening, and answering the past differently.",
    coreMeaningZh: "召唤、清算、回返、觉醒，以及用新的方式回应过去。",
    allowedThemes: ["calling", "reckoning", "awakening", "return", "accountability", "renewed response"],
    avoidThemes: ["avoidance", "numb repetition", "pure comfort", "small distraction"],
    reflectiveDirectionEn: "Turn the question toward what is asking to be answered now.",
    reflectiveDirectionZh: "把问题转向：现在有什么正在要求你回应。",
    reframingStyle: "Ask what old story is calling for a different answer."
  },
  {
    id: "the-world",
    englishName: "The World",
    chineseName: "世界",
    keywords: ["completion", "integration", "threshold", "wholeness"],
    symbolicFunction: "This card interrupts fragmentation.",
    reflectiveOperation: "It asks what belongs to the whole pattern, not only to this one problem.",
    visualSymbol: "wreath / four corners",
    coreMeaningEn: "completion, integration, wholeness, and seeing the question as part of a larger pattern.",
    coreMeaningZh: "完成、整合、整体性，以及把问题放回更大的图案中看。",
    allowedThemes: ["completion", "integration", "wholeness", "cycle completed", "larger pattern", "belonging"],
    avoidThemes: ["fragmentation", "minor urgency", "collapse", "isolated detail"],
    reflectiveDirectionEn: "Turn the question toward the whole pattern it belongs to.",
    reflectiveDirectionZh: "把问题转向：它属于哪个更完整的图案。",
    reframingStyle: "Ask what is ready to be integrated rather than solved separately."
  }
];

export function findCardByName(name: string): TarotCard | undefined {
  const lower = name.trim().toLowerCase();
  return majorArcana.find(
    (card) => card.englishName.toLowerCase() === lower || card.chineseName === name.trim()
  );
}
